hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("EDITOR", "code-insiders")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("TERMINAL", "kitty")
hl.env("PATH",
    "/home/loseardes77/.vite-plus/js_runtime/node/24.19.0/bin:/home/loseardes77/.vite-plus/bin:/home/loseardes77/.bun/bin:/home/loseardes77/.nub/bin:/home/loseardes77/.local/share/pnpm:/home/loseardes77/.local/bin:/home/loseardes77/.local/share/zinit/polaris/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/loseardes77/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/loseardes77/.cargo/bin:/home/loseardes77/.fzf/bin:/home/loseardes77/.lmstudio/bin:/home/loseardes77/.dotnet/tools")
