-- Generated by nwg-displays on 2026-10-03 at 11:57:19. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1200@59.95",
    position = "2560x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@100.0",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    vrr = 0
})
