color0 #49473c
color1 #ffb4ab
color2 #d0c895
color3 #ccc7ae
color4 #b5ceaa
color5 #d0c895
color6 #ccc7ae
color7 #e6e2dc
color8 #949183
color9 #ffb4ab
color10 #d0c895
color11 #ccc7ae
color12 #b5ceaa
color13 #d0c895
color14 #ccc7ae
color15 #e6e2dc

cursor                #e6e2dc
cursor_text_color     #141310
background            #141310
foreground            #e6e2dc
selection_foreground  #cbc6b8
selection_background  #49473c
active_border_color   #d0c895
inactive_border_color #49473c
url_color             #d0c895

active_tab_foreground   #35310b
active_tab_background   #d0c895
inactive_tab_foreground #cbc6b8
inactive_tab_background #49473c
cursor_trail_color      #cbc6b8
