color0 #44474c
color1 #ffb4ab
color2 #bdc7d8
color3 #c4c6ce
color4 #d7c0d1
color5 #bdc7d8
color6 #c4c6ce
color7 #e4e2e3
color8 #8f9196
color9 #ffb4ab
color10 #bdc7d8
color11 #c4c6ce
color12 #d7c0d1
color13 #bdc7d8
color14 #c4c6ce
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #131314
background            #131314
foreground            #e4e2e3
selection_foreground  #c5c6cc
selection_background  #44474c
active_border_color   #bdc7d8
inactive_border_color #44474c
url_color             #bdc7d8

active_tab_foreground   #27313e
active_tab_background   #bdc7d8
inactive_tab_foreground #c5c6cc
inactive_tab_background #44474c
cursor_trail_color      #c5c6cc
