cursor #e8e2d4
cursor_text_color #cdc6b4

foreground            #e8e2d4
background            #15130b
selection_foreground  #363016
selection_background  #d0c6a2
url_color             #d9c76f

color0   #15130b
color1   #f97d70
color2   #7bd96c
color3   #ffe872
color4   #ceb955
color5   #64550a
color6   #d9c76f
color7   #e3e1d6
color8   #8d8b82
color9   #ffa89f
color10  #b1ffa5
color11  #fff0a5
color12  #eedd8b
color13  #fff0a7
color14  #fff5c6
color15  #fffdf8
